#ifndef BOARAI_HARDWARE_GPSMM_ADAPTER_HPP
#define BOARAI_HARDWARE_GPSMM_ADAPTER_HPP

#include <libgpsmm.h>

#define GPSMM_STATUS_FIX STATUS_FIX
#undef STATUS_FIX

#define GPSMM_STATUS_NO_FIX STATUS_NO_FIX
#undef STATUS_NO_FIX

#endif