---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: ubuntu:bionic
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Set up ROS2
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: eloquent
      - name: Build Firmware
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: boarai
          target-ros2-distro: eloquent
...
