---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        with:
          python-version: 3.8
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Set up ROS2
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: eloquent
      - name: Build Firmware
        run: |
          source /opt/ros/eloquent/setup.bash
          colcon build --symlink-install
...
